steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/numeric-skill-315811/gcr.io/numeric-skill-315811/github.com', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/numeric-skill-315811/gcr.io/numeric-skill-315811/github.com']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'core', '--image', 'gcr.io/numeric-skill-315811/gcr.io/numeric-skill-315811/github.com', '--region', 'us-central1', '--platform', 'managed']
images:
- gcr.io/numeric-skill-315811/gcr.io/numeric-skill-315811/github.com
